---
- hosts: websever
  tasks:
    - name: change permission
      shell: sudo chmod 777 /var/run/docker.sock

    - name: login to jfrog
      shell: docker login -u manasa@abc.com -p Mandasmitha@84 ghijk.jfrog.io 
    
    - name: pull an image
      shell: docker pull ghijk.jfrog.io/test/devops_practice:{{ BUILD_NUMBER }} 

    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 ghijk.jfrog.io/test/devops_practice:{{ BUILD_NUMBER }}
 
   
